### ISSUE TITLE
fail to migration from old client 

### ISSUE THREAD

**Issue by masayil** [safe-global/safe-client-gateway-nest#604]
I maintain a safe system myself.
After I migrated from the legacy gateway client, the data returned by the config service could not be parsed.

response:
```
{"message":"Validation failed","code":42,"arguments":[]}
```
log:
```
{"level":"debug","message":{"field":"","key":"56_chain","type":"cache_miss"},"request_id":"97275849-7ca7-43cc-94cd-0c071279d321","timestamp":"2023-08-01T01:46:05.364Z"}
{"level":"warn","message":{"arguments":[],"code":42,"detail":[{"instancePath":"/nativeCurrency/logoUri","message":"must match format \"uri\"","schemaPath":"native-currency.json/properties/logoUri/format"}],"message":"Validation failed"},"request_id":"97275849-7ca7-43cc-94cd-0c071279d321","timestamp":"2023-08-01T01:46:05.606Z"}
{"level":"error","message":{"chain_id":"56","client_ip":null,"detail":"Validation failed","method":"GET","path":"/v1/chains/56","response_time_ms":244.0703477859497,"route":"/v1/chains/:chainId","status_code":500},"request_id":"97275849-7ca7-43cc-94cd-0c071279d321","timestamp":"2023-08-01T01:46:05.606Z"}
{"level":"error","message":{"message":"Validation failed","name":"HttpException","stacktrace":"HttpException: Validation failed\n    at ValidationErrorFactory.from (/root/safe-client-gateway-nest/dist/validation/providers/validation-error-factory.js:35:16)\n    at GenericValidator.validate (/root/safe-client-gateway-nest/dist/validation/providers/generic.validator.js:22:47)\n    at ChainsValidator.validate (/root/safe-client-gateway-nest/dist/domain/chains/chains.validator.js:29:38)\n    at ChainsRepository.getChain (/root/safe-client-gateway-nest/dist/domain/chains/chains.repository.js:30:36)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChainsService.getChain (/root/safe-client-gateway-nest/dist/routes/chains/chains.service.js:43:24)"},"request_id":"97275849-7ca7-43cc-94cd-0c071279d321","timestamp":"2023-08-01T01:46:05.607Z"}
```

**Comment by masayil** [comment]
Responses from legacy clients：
![image](https://github.com/safe-global/safe-client-gateway-nest/assets/65291464/bffed13f-4a1b-4a39-97e2-a5b71c63aa8f)

**Comment by masayil** [comment]
**ensRegistryAddress** Maybe this field is missing.
